#ifndef __LAPSE_CONTROLLER_HPP__
#define __LAPSE_CONTROLLER_HPP__

//some version info
#define LAPSE_CONTROLLER_VERSION_MAJOR 0
#define LAPSE_CONTROLLER_VERSION_MINOR 0
#define LAPSE_CONTROLLER_VERSION_PATCH 0

#endif //__LAPSE_CONTROLLER_HPP__
